import { useMemo, useState } from 'react';
import { ArrowDownUp, ChevronLeft, ChevronRight, Eye, MoreHorizontal, Plus, Search, SlidersHorizontal, X } from 'lucide-react';
import type { CollectionKey, BaseRecord } from '../data/models';
import { useDemoData } from '../data/context';

export interface Column { key:string; label:string; }
interface Props { title:string; eyebrow?:string; subtitle:string; collection:CollectionKey; columns:Column[]; createLabel?:string; fields?:string[]; description?:string; emptyCopy?:string; allowCreate?:boolean; }
const titleCase=(key:string)=>key.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase());
const text=(v:unknown)=>v===undefined||v===null||v===''?'—':String(v);
function getStatusClass(value:string){const s=value.toLowerCase();return s.includes('active')||s.includes('complete')||s.includes('approved')||s.includes('present')?'success':s.includes('risk')||s.includes('low stock')||s.includes('reject')?'danger':s.includes('pending')||s.includes('scheduled')||s.includes('draft')||s.includes('away')?'warning':'info';}

export default function ResourcePage({title,eyebrow='WORKSPACE',subtitle,collection,columns,createLabel='Add record',fields,description,emptyCopy='No records match your search. Try a different term or create a new record.',allowCreate=true}:Props) {
 const {data,add,update,remove}=useDemoData(); const rows=(data[collection] as BaseRecord[]);
 const [query,setQuery]=useState(''); const [statusFilter,setStatusFilter]=useState('All statuses'); const [sort,setSort]=useState('Recently updated'); const [page,setPage]=useState(1);
 const [selected,setSelected]=useState<BaseRecord|null>(null); const [edit,setEdit]=useState<BaseRecord|null>(null); const [showForm,setShowForm]=useState(false); const [draft,setDraft]=useState<Record<string,string>>({});
 const filtered=useMemo(()=>rows.filter(row=>Object.values(row).some(v=>String(v??'').toLowerCase().includes(query.toLowerCase()))&&(statusFilter==='All statuses'||row.status===statusFilter)),[rows,query,statusFilter]);
 const sorted=useMemo(()=>[...filtered].sort((a,b)=>sort==='Name A–Z'?a.name.localeCompare(b.name):String(b.updatedAt??b.id).localeCompare(String(a.updatedAt??a.id))),[filtered,sort]);
 const pageSize=8; const totalPages=Math.max(1,Math.ceil(sorted.length/pageSize)); const currentPage=Math.min(page,totalPages); const visible=sorted.slice((currentPage-1)*pageSize,currentPage*pageSize);
 const openCreate=()=>{setEdit(null);setDraft(Object.fromEntries((fields??columns.filter(c=>c.key!=='status').map(c=>c.key)).map(k=>[k,''])));setShowForm(true);};
 const openEdit=(row:BaseRecord)=>{setEdit(row);setDraft(Object.fromEntries(Object.entries(row).map(([k,v])=>[k,String(v??'')])));setShowForm(true);};
 const save=()=>{const name=draft.name||draft.employee||draft.title||'Untitled record';if(edit)update(collection,edit.id,{...draft,name} as Partial<BaseRecord>);else add(collection,{...draft,name,status:draft.status||'Active'});setShowForm(false);};
 const onDelete=(row:BaseRecord)=>{if(window.confirm(`Remove “${row.name}” from this demo workspace?`))remove(collection,row.id);};
 return <main className="page-wrap">
  <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1 className="page-title">{title}</h1><div className="page-subtitle">{subtitle}</div></div><div className="heading-actions"><button className="btn" onClick={()=>setSort(sort==='Recently updated'?'Name A–Z':'Recently updated')} data-testid={`button-sort-${collection}`}><ArrowDownUp size={14}/>{sort}</button>{allowCreate&&<button className="btn btn-primary" onClick={openCreate} data-testid={`button-create-${collection}`}><Plus size={15}/>{createLabel}</button>}</div></div>
  {description&&<div className="notice accent" style={{marginBottom:14}}>{description}</div>}
  <section className="panel">
   <div className="toolbar"><div className="search-box"><Search size={14}/><input className="field" aria-label={`Search ${title}`} placeholder={`Search ${title.toLowerCase()}…`} value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} data-testid={`input-search-${collection}`}/></div><select className="select" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} aria-label="Filter by status" data-testid={`select-status-${collection}`}><option>All statuses</option>{Array.from(new Set(rows.map(r=>r.status).filter(Boolean))).map(s=><option key={s}>{s}</option>)}</select><button className="btn btn-small" onClick={()=>{setQuery('');setStatusFilter('All statuses')}} data-testid={`button-clear-filters-${collection}`}><SlidersHorizontal size={13}/>Reset filters</button></div>
   {visible.length===0?<div className="empty-state"><div className="empty-symbol"><Search size={18}/></div><div className="empty-title">Nothing here just yet</div><div className="empty-copy">{emptyCopy}</div>{allowCreate&&<button className="btn btn-primary btn-small" onClick={openCreate} data-testid={`button-empty-create-${collection}`}><Plus size={13}/>{createLabel}</button>}</div>:
   <div className="table-wrap"><table className="data-table"><thead><tr>{columns.map(col=><th key={col.key}>{col.label}</th>)}<th>Actions</th></tr></thead><tbody>{visible.map(row=><tr key={row.id} data-testid={`row-${collection}-${row.id}`} onDoubleClick={()=>setSelected(row)}>{columns.map(col=><td key={col.key}>{col.key==='name'||col.key==='employee'?<div className="record-title">{text((row as any)[col.key])}<div className="record-sub">{text((row as any).id)}</div></div>:col.key==='status'?<span className={`pill ${getStatusClass(text((row as any)[col.key]))}`} data-testid={`status-${collection}-${row.id}`}>{text((row as any)[col.key])}</span>:text((row as any)[col.key])}</td>)}<td><div className="row-actions"><button className="icon-button" title="View details" onClick={()=>setSelected(row)} data-testid={`button-view-${row.id}`}><Eye size={14}/></button><button className="icon-button" title="Edit record" onClick={()=>openEdit(row)} data-testid={`button-edit-${row.id}`}><MoreHorizontal size={15}/></button><button className="icon-button" title="Remove record" onClick={()=>onDelete(row)} data-testid={`button-delete-${row.id}`}><X size={14}/></button></div></td></tr>)}</tbody></table></div>}
   <div className="pagination"><span>Showing {sorted.length?((currentPage-1)*pageSize+1):0}–{Math.min(currentPage*pageSize,sorted.length)} of {sorted.length} records</span><div className="pagination-actions"><button className="icon-button" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)} aria-label="Previous page" data-testid={`button-prev-${collection}`}><ChevronLeft size={15}/></button><span style={{padding:'5px 6px'}}>{currentPage} / {totalPages}</span><button className="icon-button" disabled={currentPage>=totalPages} onClick={()=>setPage(currentPage+1)} aria-label="Next page" data-testid={`button-next-${collection}`}><ChevronRight size={15}/></button></div></div>
  </section>
  {selected&&<div className="detail-overlay" onClick={()=>setSelected(null)}><aside className="detail-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><div className="detail-label">{title} · {selected.id}</div><h2 className="detail-title">{selected.name}</h2>{selected.status&&<span className={`pill ${getStatusClass(selected.status)}`}>{selected.status}</span>}</div><button className="icon-button" onClick={()=>setSelected(null)} aria-label="Close details" data-testid="button-close-detail"><X size={18}/></button></div><section className="detail-section"><h3>Record details</h3>{Object.entries(selected).filter(([k])=>!['id','organizationId','name'].includes(k)).map(([k,v])=><div className="detail-line" key={k}><span>{titleCase(k)}</span><span>{text(v)}</span></div>)}</section><section className="detail-section"><h3>Organization context</h3><div className="detail-line"><span>Organization</span><span>Northstar Collective</span></div><div className="detail-line"><span>Record ID</span><span>{selected.id}</span></div><div className="detail-line"><span>Storage</span><span>Saved locally in this browser</span></div></section><div style={{display:'flex',gap:8,marginTop:18}}><button className="btn btn-primary" onClick={()=>{openEdit(selected);setSelected(null)}} data-testid="button-edit-detail">Edit record</button><button className="btn" onClick={()=>setSelected(null)} data-testid="button-dismiss-detail">Close</button></div></aside></div>}
  {showForm&&<div className="detail-overlay" onClick={()=>setShowForm(false)}><section className="detail-drawer" style={{width:'min(520px,100%)'}} onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><div className="detail-label">{edit?'EDIT RECORD':'NEW RECORD'}</div><h2 className="detail-title">{edit?'Update':'Create'} {title.toLowerCase().replace(/s$/,'')}</h2></div><button className="icon-button" onClick={()=>setShowForm(false)} aria-label="Close form" data-testid="button-close-record-form"><X size={18}/></button></div><form onSubmit={e=>{e.preventDefault();save()}}><div className="form-grid">{(fields??columns.filter(c=>c.key!=='status').map(c=>c.key)).map(key=><div className="form-field" key={key}><label htmlFor={`draft-${key}`}>{titleCase(key)}</label><input id={`draft-${key}`} className="field" value={draft[key]??''} onChange={e=>setDraft({...draft,[key]:e.target.value})} placeholder={titleCase(key)} data-testid={`input-form-${key}`}/></div>)}<div className="form-field"><label htmlFor="draft-status">Status</label><select id="draft-status" className="select" value={draft.status||'Active'} onChange={e=>setDraft({...draft,status:e.target.value})} data-testid="select-form-status">{['Active','Pending','In progress','Complete','At risk','Approved','Rejected','Draft','Scheduled','Low stock','Connected','Not connected'].map(s=><option key={s}>{s}</option>)}</select></div></div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:24}}><button type="button" className="btn" onClick={()=>setShowForm(false)} data-testid="button-cancel-record">Cancel</button><button className="btn btn-primary" type="submit" data-testid="button-save-record">{edit?'Save changes':'Create record'}</button></div><div className="panel-caption" style={{marginTop:14}}>Saved to this browser only. No server changes are made.</div></form></section></div>}
 </main>;
}