import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Check, Copy, RotateCcw, ShieldCheck } from 'lucide-react';
import { useDemoData } from '../data/context';
import ResourcePage from '../components/ResourcePage';
import type { CollectionKey } from '../data/models';

export function AuditPage(){return <ResourcePage eyebrow="GOVERNANCE" title="Audit trail" subtitle="A readable record of actions in this local workspace." collection="audit" columns={[{key:'name',label:'Event'},{key:'actor',label:'Actor'},{key:'action',label:'Action'},{key:'target',label:'Target'},{key:'timestamp',label:'Timestamp'},{key:'source',label:'Area'}]} createLabel="Add audit note" fields={['name','actor','action','target','timestamp','source']} description="Audit events shown here are seeded or created in this browser. They are not tamper-proof or server verified."/>}
export function VerificationPage(){
 const {data}=useDemoData();
 return <main className="page-wrap"><div className="page-heading"><div><div className="eyebrow">GOVERNANCE · RECORD INTEGRITY</div><h1 className="page-title">Verification</h1><div className="page-subtitle">Inspect the provenance of records without overstating what this demo verifies.</div></div><span className="pill warning">Placeholder</span></div><div className="notice" style={{marginBottom:15}}>Chain data is a placeholder. No blockchain, cryptographic proof, external ledger, or verification service is connected.</div><div className="dashboard-grid"><section className="panel panel-pad"><div className="panel-head"><div><div className="panel-title">Local record snapshot</div><div className="panel-caption">A simple browser-side inventory of seeded record groups</div></div><ShieldCheck size={17} color="#7a8e81"/></div>{(['employees','tasks','approvals','documents','assets'] as CollectionKey[]).map(key=><div className="detail-line" key={key}><span>{key[0].toUpperCase()+key.slice(1)}</span><span>{(data[key] as unknown[]).length} records</span></div>)}<div className="detail-line"><span>Organization ID</span><span>{data.organization.id}</span></div></section><section className="panel panel-pad"><div className="eyebrow">CHAIN REFERENCE · PLACEHOLDER</div><div style={{fontFamily:'monospace',fontSize:12,color:'#687267',margin:'14px 0',wordBreak:'break-all'}}>0x0000000000000000000000000000000000000000</div><div className="detail-line"><span>Network</span><span>Not connected</span></div><div className="detail-line"><span>Proof status</span><span><span className="pill warning">Not verified</span></span></div><button className="btn" style={{marginTop:17}} onClick={()=>navigator.clipboard?.writeText(data.organization.id)} data-testid="button-copy-org-id"><Copy size={13}/>Copy local organization ID</button></section></div><div className="panel panel-pad" style={{marginTop:14}}><div className="panel-title">What can be relied on here?</div><p className="page-subtitle" style={{maxWidth:760,lineHeight:1.8}}>The UI can show record IDs and local edits. Browser storage is editable and may be cleared, so it is not an audit-grade source of truth. A future server implementation would need signed events, durable storage and an explicit verification provider.</p></div></main>;
}
export function OrganizationSettings(){
 const {data,reset,updateOrganization}=useDemoData(); const [saved,setSaved]=useState(false); const [name,setName]=useState(data.organization.name); const [industry,setIndustry]=useState(data.organization.industry); const [timezone,setTimezone]=useState(data.organization.timezone);
 useEffect(()=>{setName(data.organization.name);setIndustry(data.organization.industry);setTimezone(data.organization.timezone);},[data.organization.name,data.organization.industry,data.organization.timezone]);
 const save=()=>{updateOrganization({name,industry,timezone});setSaved(true);};
 const resetAll=()=>{if(window.confirm('Reset every locally saved demo change and restore the seeded Northstar workspace?')){reset();setName('Northstar Collective');setIndustry('Professional services');setTimezone('America/Chicago');setSaved(false);}};
 return <main className="page-wrap"><div className="page-heading"><div><div className="eyebrow">SETTINGS</div><h1 className="page-title">Organization</h1><div className="page-subtitle">Workspace identity and operating context.</div></div><button className="btn btn-danger" onClick={resetAll} data-testid="button-reset-demo-data"><RotateCcw size={13}/>Reset demo data</button></div><div className="settings-grid"><div className="panel settings-menu">{[['Organization','/settings/organization'],['Users','/settings/users'],['Roles & permissions','/settings/roles'],['Modules','/settings/modules'],['Integrations','/settings/integrations']].map(([label,path])=><Link href={path} className={`nav-link ${path==='/settings/organization'?'active':''}`} key={path}>{label}</Link>)}</div><section className="panel panel-pad"><div className="panel-title">Organization profile</div><div className="panel-caption">Changes persist in local browser storage. No server organization is provisioned.</div><div className="form-grid" style={{marginTop:20}}><div className="form-field full"><label htmlFor="setting-org-name">Organization name</label><input id="setting-org-name" className="field" value={name} onChange={e=>setName(e.target.value)} data-testid="input-setting-org-name"/></div><div className="form-field"><label htmlFor="setting-industry">Operating context</label><input id="setting-industry" className="field" value={industry} onChange={e=>setIndustry(e.target.value)} data-testid="input-setting-industry"/></div><div className="form-field"><label htmlFor="setting-timezone">Timezone</label><input id="setting-timezone" className="field" value={timezone} onChange={e=>setTimezone(e.target.value)} data-testid="input-setting-timezone"/></div><div className="form-field"><label>Organization ID</label><input className="field" value={data.organization.id} readOnly/></div></div><div style={{display:'flex',alignItems:'center',gap:12,marginTop:18}}><button className="btn btn-primary" onClick={save} data-testid="button-save-organization">Save changes <Check size={13}/></button>{saved&&<span className="panel-caption" data-testid="text-organization-saved">Saved locally.</span>}</div></section></div></main>;
}
export function UsersPage(){return <ResourcePage eyebrow="SETTINGS" title="Users" subtitle="People with workspace access and their current roles." collection="users" columns={[{key:'name',label:'User'},{key:'email',label:'Email'},{key:'role',label:'Role'},{key:'lastActive',label:'Last active'},{key:'status',label:'Status'}]} createLabel="Invite user" fields={['name','email','role']} description="Invitations are local demo records. No email or account provisioning is performed."/>}
export function RolesPage(){return <ResourcePage eyebrow="SETTINGS" title="Roles & permissions" subtitle="Understand the access boundaries represented in this demo." collection="roles" columns={[{key:'name',label:'Role'},{key:'users',label:'People'},{key:'permissions',label:'Permissions summary'},{key:'scope',label:'Scope'},{key:'status',label:'Status'}]} createLabel="Create role" fields={['name','users','permissions','scope']} description="These role descriptions are illustrative. Authorization is not enforced in this frontend-only release."/>}
export function ModulesPage(){
 const {data,update}=useDemoData();
 return <main className="page-wrap"><div className="page-heading"><div><div className="eyebrow">SETTINGS</div><h1 className="page-title">Modules</h1><div className="page-subtitle">Choose which areas appear in your workspace configuration.</div></div></div><div className="panel">{data.modules.map(m=><div key={m.id} style={{padding:'17px 20px',borderBottom:'1px solid #efede6',display:'flex',alignItems:'center',gap:16}} data-testid={`module-row-${m.id}`}><div style={{flex:1}}><div className="record-title">{m.name}</div><div className="record-sub">{m.description}</div></div><span className={`pill ${m.enabled?'success':'warning'}`}>{m.enabled?'Enabled':'Paused'}</span><button className={`btn btn-small ${m.enabled?'':'btn-primary'}`} onClick={()=>update('modules',m.id,{enabled:!m.enabled,status:m.enabled?'Pending':'Active'})} data-testid={`button-toggle-module-${m.id}`}>{m.enabled?'Pause':'Enable'}</button></div>)}</div><div className="notice" style={{marginTop:14}}>Module preferences update the navigation configuration only in this demo. No data is deleted when a module is paused.</div></main>;
}
export function IntegrationsPage(){return <ResourcePage eyebrow="SETTINGS" title="Integrations" subtitle="Connection points prepared for future configuration." collection="integrations" columns={[{key:'name',label:'Service'},{key:'description',label:'Purpose'},{key:'state',label:'Connection status'},{key:'status',label:'State'}]} allowCreate={false} description="No integrations are connected. Each status is an explicit placeholder; there is no sync, token storage, or external API activity."/>}