import { useMemo, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { ArrowRight, ArrowUpRight, ClipboardCheck, Clock3, Users, CheckSquare, Activity, ChevronDown, RefreshCw } from 'lucide-react';
import { useDemoData } from '../data/context';

function Metric({label,value,change,Icon}:{label:string;value:string;change:string;Icon:any}){return <article className="panel metric-card" data-testid={`metric-${label.toLowerCase().replaceAll(' ','-')}`}><Icon className="metric-icon" size={17}/><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-foot"><span className="metric-change">{change}</span> <span style={{color:'#929087'}}>from last month</span></div></article>}
export default function Dashboard(){
 const {data}=useDemoData(); const [,setLocation]=useLocation(); const [period,setPeriod]=useState('This month'); const [refreshed,setRefreshed]=useState('just now');
 const pending=data.approvals.filter(a=>a.status==='Pending').length;
 const attention=[
  {id:'attention-approval',title:`${pending} approvals need a decision`,meta:'Oldest request submitted Mar 6',href:'/workspace/approvals',mark:'warning'},
  {id:'attention-task',title:'Research agreement is marked at risk',meta:'Owner: Jonah Patel · due Mar 21',href:'/workspace/tasks',mark:'danger'},
  {id:'attention-inventory',title:'Two inventory items below reorder point',meta:'Chicago Office · workplace supplies',href:'/operations/inventory',mark:'warning'}
 ];
 const taskDone=data.tasks.filter(t=>t.status==='Complete').length;
 const allTasks=data.tasks.length;
 const bars=[38,48,46,59,62,74,82];
 const recent=data.activity.slice(0,4);
 const monthLabel=useMemo(()=>period==='This month'?'March 2025':'Q1 2025',[period]);
 return <main className="page-wrap">
  <div className="page-heading"><div><div className="eyebrow">MONDAY, MARCH 17, 2025 · EXECUTIVE OVERVIEW</div><h1 className="page-title">Good morning, Sofia.</h1><div className="page-subtitle">Here’s the shape of Northstar Collective today.</div></div><div className="heading-actions"><select className="select" value={period} onChange={e=>setPeriod(e.target.value)} aria-label="Dashboard date range" data-testid="select-dashboard-period"><option>This month</option><option>This quarter</option></select><button className="btn" onClick={()=>setRefreshed(new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}))} data-testid="button-refresh-dashboard"><RefreshCw size={13}/>Refresh view</button></div></div>
  <div className="metric-grid"><Metric label="Organizational health" value={`${data.kpis[0]?.value ?? '87'} / 100`} change="+3.2 pts" Icon={Activity}/><Metric label="People across 3 sites" value="90" change="+4 this quarter" Icon={Users}/><Metric label="Tasks on track" value={`${Math.round(((allTasks-taskDone)/Math.max(1,allTasks))*100)}%`} change={`${allTasks-taskDone} open items`} Icon={CheckSquare}/><Metric label="Awaiting decision" value={String(pending).padStart(2,'0')} change="4 need attention" Icon={ClipboardCheck}/></div>
  <div className="dashboard-grid">
   <section className="panel panel-pad"><div className="panel-head"><div><div className="panel-title">Organizational pulse</div><div className="panel-caption">A steady view of execution through {monthLabel.toLowerCase()}</div></div><span className="pill success">+3.2 pts</span></div><div style={{display:'flex',alignItems:'center',gap:22}}><div style={{minWidth:120}}><div style={{font:'700 38px var(--app-font-serif)',letterSpacing:'-1.5px',color:'#3e5549'}}>87<span style={{fontSize:15,color:'#929087'}}>/100</span></div><div style={{fontSize:10,color:'#85837a',marginTop:4}}>Health index</div></div><div style={{flex:1}}><div className="chart-wrap"><div className="chart-bars">{bars.map((v,i)=><div className="chart-col" key={i}><div className="bar" style={{height:`${v}%`}}/><div className="bar alt" style={{height:`${Math.max(22,v-26)}%`}}/></div>)}</div><div className="chart-labels"><span>Sep</span><span>Oct</span><span>Nov</span><span>Dec</span><span>Jan</span><span>Feb</span><span>Mar</span></div></div></div></div><div style={{borderTop:'1px solid #efede6',marginTop:12,paddingTop:12,display:'flex',gap:20,flexWrap:'wrap'}}><div><span className="panel-caption">Team pulse</span><div style={{fontSize:13,fontWeight:700,color:'#45564a',marginTop:4}}>4.3 <span style={{fontSize:10,color:'#8c8a81'}}>/ 5</span></div></div><div><span className="panel-caption">Approval turnaround</span><div style={{fontSize:13,fontWeight:700,color:'#45564a',marginTop:4}}>1.8 days</div></div><div><span className="panel-caption">Tasks completed</span><div style={{fontSize:13,fontWeight:700,color:'#45564a',marginTop:4}}>{taskDone} <span style={{fontSize:10,color:'#8c8a81'}}>of {allTasks}</span></div></div></div></section>
   <section className="panel panel-pad"><div className="panel-head"><div><div className="panel-title">Needs your attention</div><div className="panel-caption">A short list of meaningful next steps</div></div><span className="pill warning">3 items</span></div><div className="attention-list">{attention.map(item=><div className="attention-row" key={item.id}><span className="attention-mark" style={{background:item.mark==='danger'?'#ad675e':undefined}}/><div style={{minWidth:0}}><div className="row-main">{item.title}</div><div className="row-meta">{item.meta}</div></div><Link href={item.href} className="icon-button row-tail" aria-label={`Open ${item.title}`} data-testid={`link-${item.id}`}><ArrowRight size={14}/></Link></div>)}</div></section>
  </div>
  <div className="dashboard-lower">
   <section className="panel panel-pad"><div className="panel-head"><div><div className="panel-title">Tasks over time</div><div className="panel-caption">Progress across shared priorities</div></div><Link href="/workspace/tasks" className="btn btn-small">Open tasks <ArrowRight size={12}/></Link></div><div className="mini-bars">{[42,55,51,67,73,65,84,76,91,81,94,88].map((v,i)=><div className="mini-bar" key={i} style={{height:`${v}%`}} title={`${v}%`}/>)}</div><div className="chart-labels" style={{justifyContent:'space-between'}}><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>Week 4</span></div></section>
   <section className="panel panel-pad"><div className="panel-head"><div><div className="panel-title">Recent activity</div><div className="panel-caption">What has changed across the organization</div></div><Link href="/workspace/activity" className="btn btn-small">View all <ArrowRight size={12}/></Link></div><div className="activity-list">{recent.map((item,i)=><div className="activity-row" key={item.id}><span className="avatar" style={{width:27,height:27}}>{item.actor.split(' ').map(n=>n[0]).join('')}</span><div><div className="row-main">{item.actor} <span style={{fontWeight:400,color:'#85837a'}}>{item.action}</span></div><div className="row-meta">{item.target} · {item.time}</div></div>{i===0&&<span className="pill success row-tail">New</span>}</div>)}</div></section>
  </div>
  <div style={{display:'flex',gap:8,alignItems:'center',justifyContent:'flex-end',marginTop:15,fontSize:10,color:'#96938a'}}><Clock3 size={12}/> Snapshot updated {refreshed} <button className="btn btn-small btn-quiet" onClick={()=>setLocation('/intelligence/insights')} data-testid="button-open-insights">Review sample insights <ArrowUpRight size={12}/></button></div>
 </main>;
}