import { useState } from 'react';
import { Check, X } from 'lucide-react';
import { useDemoData } from '../data/context';
import ResourcePage from '../components/ResourcePage';
import type { Approval } from '../data/models';

export function ApprovalsPage(){
 const {data,update}=useDemoData(); const [filter,setFilter]=useState('Pending');
 const rows=data.approvals.filter(r=>filter==='All'||r.status===filter);
 return <main className="page-wrap"><div className="page-heading"><div><div className="eyebrow">WORKSPACE · DECISIONS</div><h1 className="page-title">Approvals</h1><div className="page-subtitle">A clear queue for decisions that keep work moving.</div></div><span className="pill warning">{data.approvals.filter(a=>a.status==='Pending').length} pending</span></div><section className="panel"><div className="toolbar"><div style={{fontSize:11,color:'#8b8980',marginRight:'auto'}}>Review a request, then record your decision.</div><select className="select" value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Approval status filter" data-testid="select-approval-filter"><option>Pending</option><option>All</option><option>Approved</option><option>Rejected</option></select></div>{rows.length===0?<div className="empty-state"><div className="empty-title">No approvals in this view</div><div className="empty-copy">You are clear for now. Completed decisions remain available in All.</div></div>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Request</th><th>Type</th><th>Requester</th><th>Submitted</th><th>Amount</th><th>Status</th><th>Decision</th></tr></thead><tbody>{rows.map((a:Approval)=><tr key={a.id} data-testid={`row-approval-${a.id}`}><td><div className="record-title">{a.name}</div><div className="record-sub">{a.id} · to {a.approver}</div></td><td>{a.type}</td><td>{a.requester}</td><td>{a.submitted}</td><td style={{fontWeight:700}}>{a.amount}</td><td><span className={`pill ${a.status==='Pending'?'warning':a.status==='Approved'?'success':'danger'}`} data-testid={`status-approval-${a.id}`}>{a.status}</span></td><td><div className="row-actions">{a.status==='Pending'?<><button className="btn btn-small" onClick={()=>update('approvals',a.id,{status:'Rejected'})} data-testid={`button-reject-${a.id}`}><X size={12}/>Decline</button><button className="btn btn-small btn-primary" onClick={()=>update('approvals',a.id,{status:'Approved'})} data-testid={`button-approve-${a.id}`}><Check size={12}/>Approve</button></>:<span style={{fontSize:10,color:'#8b8980'}}>Decision recorded</span>}</div></td></tr>)}</tbody></table></div>}<div className="pagination"><span>Showing {rows.length} of {data.approvals.length} requests</span><span>Decisions saved locally</span></div></section><div className="notice" style={{marginTop:13}}>Approvals are demo records. Recording a decision updates this browser only; no notification or payment action is triggered.</div></main>;
}
export function TasksPage(){return <ResourcePage eyebrow="WORKSPACE" title="Tasks" subtitle="Shared commitments with a clear owner, deadline and current state." collection="tasks" columns={[{key:'name',label:'Task'},{key:'owner',label:'Owner'},{key:'category',label:'Area'},{key:'dueDate',label:'Due date'},{key:'priority',label:'Priority'},{key:'status',label:'Status'}]} createLabel="Create task" fields={['name','owner','category','dueDate','priority']}/>}
export function ActivityPage(){return <ResourcePage eyebrow="WORKSPACE" title="Organizational activity" subtitle="A shared view of recent changes across the Northstar workspace." collection="activity" columns={[{key:'name',label:'Activity'},{key:'actor',label:'Person'},{key:'action',label:'Action'},{key:'target',label:'Record'},{key:'time',label:'When'},{key:'status',label:'State'}]} createLabel="Add activity note" fields={['name','actor','action','target','time']}/>}